version: "3.7"

services:
    app:
        build:
            context: ./
        depends_on:
            - stan
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 5001:5001
            - 9229:9229
        environment:
            - NATS_URL=nats://stan:4222
        command: npm run dev

    stan:
        image: nats-streaming
        ports:
            - 8222:8222

    mongo:
        image: mongo
        ports:
            - 27017:27017
